# See: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#about-the-dependabotyml-file
version: 2

updates:
  - package-ecosystem: npm
    directory: /
    assignees:
      - per1234
    labels:
      - "topic: infrastructure"
    open-pull-requests-limit: 100
    schedule:
      interval: daily
